version: '3.7'

services:

    php:
        container_name: php
        image: maciejslawik/php-fpm-xdebug:latest
        links:
            - elasticsearch
            - rabbitmq
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST_IP} idekey=${XDEBUG_IDE_KEY}"
            PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG_SERVERNAME}"
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}

    nginx:
        container_name: nginx
        image: maciejslawik/nginx:latest
        ports:
            - ${NGINX_PORT}:80
        links:
            - php
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - ./docker/nginx:/etc/nginx/sites-available
            - .:/var/www/html

#    nginx:
#        container_name: nginx-varnish-magento2
#        image: maciejslawik/nginx:latest
#        ports:
#            - ${NGINX_PORT}:8000
#            - ${NGINX_PROXY_UNSECURE_PORT}:80
#            - ${NGINX_PROXY_SECURE_PORT}:443
#        links:
#            - php
#        environment:
#            COLUMNS: ${TERMINAL_COLS}
#            LINES: ${TERMINAL_LINES}
#        volumes:
#            - ./docker/nginx-varnish-magento2:/etc/nginx/sites-available
#            - .:/var/www/html

    apache:
        container_name: apache
        image: maciejslawik/apache2:latest
        volumes:
            - ./docker/apache:/etc/apache2/sites-enabled
            - .:/var/www/html
        ports:
            - ${APACHE_PORT}:80
        links:
            - php
        environment:
            APACHE_UID: ${APACHE_UID}
            APACHE_GID: ${APACHE_GID}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    varnish:
        container_name: ${DOMAIN_NAME}
        image: eeacms/varnish
        ports:
            - ${VARNISH_PORT}:6081
        links:
            - nginx
        environment:
            BACKENDS: ${DOMAIN_NAME}
            BACKENDS_PORT: ${APPSERVER_PORT}
            BACKENDS_PROBE_INTERVAL: 6000s
        volumes:
            - ./docker/varnish/default.vcl:/etc/varnish/default.vcl

#    varnish:
#        container_name: ${DOMAIN_NAME}
#        image: eeacms/varnish
#        ports:
#            - ${VARNISH_PORT}:6081
#        links:
#            - nginx-varnish-magento2
#        environment:
#            BACKENDS: ${DOMAIN_NAME}
#            BACKENDS_PORT: ${APPSERVER_PORT}
#            BACKENDS_PROBE_INTERVAL: 6000s
#        volumes:
#            - ./docker/varnish-magento2/default.vcl:/etc/varnish/default.vcl

    mysql:
        container_name: db
        image: mysql
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASS}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - ./docker/data/mysql:/var/lib/mysql

    postgresql:
        container_name: postgresql
        image: sameersbn/postgresql:9.6-2
        ports:
            - ${POSTGRESQL_PORT}:5432
        environment:
            DB_USER: ${POSTGRESQL_USER}
            DB_PASS: ${POSTGRESQL_PASS}
            DB_NAME: ${POSTGRESQL_DB}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - postgreqsl_data:/var/lib/postgresql/

    adminer:
        container_name: adminer
        image: adminer
        ports:
            - ${ADMINER_PORT}:8080
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:6.5.3
        ports:
            - ${ELASTICSEARCH_PORT}:9200
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
            - elasticsearch_config:/usr/share/elasticsearch/config

    redis:
        container_name: redis
        image: bitnami/redis:latest
        ports:
            - ${REDIS_PORT}:6379
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - redis_data:/bitnami

    mongodb:
        container_name: mongodb
        image: bitnami/mongodb:latest
        ports:
            - ${MONGODB_PORT}:27017
        environment:
            MONGODB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - mongodb_data:/bitnami

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - ${RABBITMQ_MANAGEMENT_PORT}:15672
          - ${RABBITMQ_MAIN_PORT}:5672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    selenium:
        container_name: selenium
        image: selenium/standalone-firefox
        ports:
            - ${SELENIUM_PORT}:4444
        shm_size: '2gb'
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    blackfire:
        container_name: blackfire
        image: blackfire/blackfire
        environment:
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}

volumes:
    postgreqsl_data:
    redis_data:
    mongodb_data:
    elasticsearch_data:
    elasticsearch_config:

