version: '3.1'

services:
    php:
        image: maciejslawik/php-fpm-xdebug:latest
        links:
            - elasticsearch
            - rabbitmq
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST_IP} idekey=${XDEBUG_IDE_KEY}"
            PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG_SERVERNAME}"
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
    nginx:
        image: maciejslawik/nginx:latest
        ports:
            - ${NGINX_PORT}:80
        links:
            - php
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - ./docker/nginx:/etc/nginx/sites-available
            - .:/var/www/html
    apache:
        image: maciejslawik/apache2:latest
        volumes:
            - ./docker/apache:/etc/apache2/sites-enabled
            - .:/var/www/html
        ports:
            - ${APACHE_PORT}:80
        links:
            - php
        environment:
            APACHE_UID: ${APACHE_UID}
            APACHE_GID: ${APACHE_GID}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    mysql:
        image: mysql
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASS}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
    postgresql:
        image: sameersbn/postgresql:9.6-2
        ports:
            - ${POSTGRESQL_PORT}:5432
        environment:
            DB_USER: ${POSTGRESQL_USER}
            DB_PASS: ${POSTGRESQL_PASS}
            DB_NAME: ${POSTGRESQL_DB}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - postgreqsl_data:/var/lib/postgresql/
    adminer:
        image: adminer
        ports:
            - ${ADMINER_PORT}:8080
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    elasticsearch:
        image: elasticsearch:6.5.3
        ports:
            - ${ELASTICSEARCH_PORT}:9200
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
            - elasticsearch_config:/usr/share/elasticsearch/config

    redis:
        image: bitnami/redis:latest
        ports:
            - ${REDIS_PORT}:6379
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - redis_data:/bitnami

    mongodb:
        image: bitnami/mongodb:latest
        ports:
            - ${MONGODB_PORT}:27017
        environment:
            MONGODB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - mongodb_data:/bitnami

    rabbitmq:
        image: rabbitmq:3-management
        ports:
          - ${RABBITMQ_MANAGEMENT_PORT}:15672
          - ${RABBITMQ_MAIN_PORT}:5672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    selenium:
        image: selenium/standalone-firefox
        ports:
            - ${SELENIUM_PORT}:4444
        shm_size: '2gb'
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    blackfire:
        image: blackfire/blackfire
        environment:
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}

volumes:
    postgreqsl_data:
    redis_data:
    mongodb_data:
    elasticsearch_data:
    elasticsearch_config:

